sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shenrx48/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shenrx48/docker-react npm run test -- --coverage
